### register admin
POST http://localhost:5000/api/admin/register
Content-Type: application/json

{
    "name": "admin4",
    "username": "admin4",
    "password": "admin4"
}


### login admin
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
    "username": "admin2",
    "password": "admin2"
}


### get all admins
GET http://localhost:5000/api/admin/admins
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2NDI5NTYzNywiZXhwIjoxNjY0Mjk5MjM3fQ.Ib9BfMwQT2tktDgnrzgppmYGb2xO01zBV3TtPSKIzXg


### get all students
GET http://localhost:5000/api/admin/students
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2NDI5NTYzNywiZXhwIjoxNjY0Mjk5MjM3fQ.Ib9BfMwQT2tktDgnrzgppmYGb2xO01zBV3TtPSKIzXg


### student details
GET http://localhost:5000/api/admin/student/633322b52852c693af20c149
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2NDI5NTYzNywiZXhwIjoxNjY0Mjk5MjM3fQ.Ib9BfMwQT2tktDgnrzgppmYGb2xO01zBV3TtPSKIzXg


### delete student
DELETE http://localhost:5000/api/admin/student/632dbea3c2a694f7d4b965bc
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MjQyMywiZXhwIjoxNjYzOTQ2MDIzfQ.HbzWe6hgPAY7LKo-UR5x1rw6H6jeQGfOb5bV00I2t9U


### delete bulk students
DELETE http://localhost:5000/api/admin/students/bulk
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRjZjgwNjRjNmI4OWNlZDNhNzU2YiIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImFkbWluIjp0cnVlLCJpYXQiOjE2NjQ3MTkxNjQsImV4cCI6MTY2NDcyMjc2NH0.qVwrRmxqb_6KkLT_3nKlcWqSF_pDiEYjr1k98-goqTk


### pending payments
GET http://localhost:5000/api/admin/payment/pending
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2NDI5NTYzNywiZXhwIjoxNjY0Mjk5MjM3fQ.Ib9BfMwQT2tktDgnrzgppmYGb2xO01zBV3TtPSKIzXg


### approve payment
PUT http://localhost:5000/api/admin/payment/approve/633322b52852c693af20c149
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2NDI5NTYzNywiZXhwIjoxNjY0Mjk5MjM3fQ.Ib9BfMwQT2tktDgnrzgppmYGb2xO01zBV3TtPSKIzXg


### reject payment
PUT http://localhost:5000/api/admin/payment/reject/6333225f2852c693af20c13d
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2NDI5NTYzNywiZXhwIjoxNjY0Mjk5MjM3fQ.Ib9BfMwQT2tktDgnrzgppmYGb2xO01zBV3TtPSKIzXg


### status tShirt
PUT http://localhost:5000/api/admin/status/tShirt/633322b52852c693af20c149
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2NDI5NTYzNywiZXhwIjoxNjY0Mjk5MjM3fQ.Ib9BfMwQT2tktDgnrzgppmYGb2xO01zBV3TtPSKIzXg


### status attendance
PUT http://localhost:5000/api/admin/status/attendance/633322b52852c693af20c149
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2NDI5NTYzNywiZXhwIjoxNjY0Mjk5MjM3fQ.Ib9BfMwQT2tktDgnrzgppmYGb2xO01zBV3TtPSKIzXg

{
    "day": "day2"
}


### status food
PUT http://localhost:5000/api/admin/status/food/633322b52852c693af20c149
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2NDI5NTYzNywiZXhwIjoxNjY0Mjk5MjM3fQ.Ib9BfMwQT2tktDgnrzgppmYGb2xO01zBV3TtPSKIzXg

{
    "day": "day2"
}