### register admin
POST http://localhost:5000/api/admin/register
Content-Type: application/json

{
    "name": "admin4",
    "username": "admin4",
    "password": "admin4"
}


### login admin
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
    "username": "admin2",
    "password": "admin2"
}


### get all admins
GET http://localhost:5000/api/admin/admins
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MzU2MSwiZXhwIjoxNjYzOTQ3MTYxfQ.QyrJNoU07p-6985c5QO8cSMw2pgQtB6bB6CbwCseEA4


### get all students
GET http://localhost:5000/api/admin/students
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MjQyMywiZXhwIjoxNjYzOTQ2MDIzfQ.HbzWe6hgPAY7LKo-UR5x1rw6H6jeQGfOb5bV00I2t9U


### student details
GET http://localhost:5000/api/admin/student/632dbeb6c2a694f7d4b965c0
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MjQyMywiZXhwIjoxNjYzOTQ2MDIzfQ.HbzWe6hgPAY7LKo-UR5x1rw6H6jeQGfOb5bV00I2t9U


### delete student
DELETE http://localhost:5000/api/admin/student/632dbea3c2a694f7d4b965bc
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MjQyMywiZXhwIjoxNjYzOTQ2MDIzfQ.HbzWe6hgPAY7LKo-UR5x1rw6H6jeQGfOb5bV00I2t9U


### approve payment
PUT http://localhost:5000/api/admin/payment/approve/632dbeb6c2a694f7d4b965c0
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MjQyMywiZXhwIjoxNjYzOTQ2MDIzfQ.HbzWe6hgPAY7LKo-UR5x1rw6H6jeQGfOb5bV00I2t9U


### reject payment
PUT http://localhost:5000/api/admin/payment/reject/632dbebcc2a694f7d4b965c3
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MjQyMywiZXhwIjoxNjYzOTQ2MDIzfQ.HbzWe6hgPAY7LKo-UR5x1rw6H6jeQGfOb5bV00I2t9U


### status tShirt
PUT http://localhost:5000/api/admin/status/tShirt/632dbeb6c2a694f7d4b965c0
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MjQyMywiZXhwIjoxNjYzOTQ2MDIzfQ.HbzWe6hgPAY7LKo-UR5x1rw6H6jeQGfOb5bV00I2t9U


### status attending
PUT http://localhost:5000/api/admin/status/attending/632dbeb6c2a694f7d4b965c0
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MjQyMywiZXhwIjoxNjYzOTQ2MDIzfQ.HbzWe6hgPAY7LKo-UR5x1rw6H6jeQGfOb5bV00I2t9U


### status food
PUT http://localhost:5000/api/admin/status/food/632dbeb6c2a694f7d4b965c0
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMmRiZWZiYzJhNjk0ZjdkNGI5NjVkMCIsInVzZXJuYW1lIjoiYWRtaW4yIiwibmFtZSI6ImFkbWluMiIsImlhdCI6MTY2Mzk0MjQyMywiZXhwIjoxNjYzOTQ2MDIzfQ.HbzWe6hgPAY7LKo-UR5x1rw6H6jeQGfOb5bV00I2t9U