### register student
POST http://localhost:5000/api/student/register
Content-Type: application/json

{
    "name": "Hello Nigga",
    "studentID": "01620106009",
    "phone": "01309897793",
    "password": "test"
}


### login student
POST http://localhost:5000/api/student/login
Content-Type: application/json

{
    "studentID": "01620106009",
    "password": "test"
}


### get student details
GET http://localhost:5000/api/student/myDetails
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjYwNDUwYjlhNTRiM2Y4MWQzN2ZkOCIsInN0dWRlbnRJRCI6IjAxNjIwMTA2MDA5IiwibmFtZSI6IkhlbGxvIE5pZ2dhIiwicGhvbmUiOiIwMTMwOTg5Nzc5MyIsImlzUGFpZCI6ZmFsc2UsImlhdCI6MTY2MzQzNTg2NCwiZXhwIjoxNjYzNDM5NDY0fQ.Zl3AUlJt7j6GmLzYvtuFfSDUXVzAbXubr1QTaolLxdo


### update student details
PUT http://localhost:5000/api/student/details
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjYwNDUwYjlhNTRiM2Y4MWQzN2ZkOCIsInN0dWRlbnRJRCI6IjAxNjIwMTA2MDA5IiwibmFtZSI6IkhlbGxvIE5pZ2dhIiwicGhvbmUiOiIwMTMwOTg5Nzc5MyIsImlzUGFpZCI6ZmFsc2UsImlhdCI6MTY2MzQzNTg2NCwiZXhwIjoxNjYzNDM5NDY0fQ.Zl3AUlJt7j6GmLzYvtuFfSDUXVzAbXubr1QTaolLxdo

{
    "name": "Hello Nigga",
    "phone": "01309897793"
}