### register student
POST http://localhost:5000/api/student/register
Content-Type: application/json

{
    "name": "Student 20",
    "studentID": "016201060020",
    "phone": "01309897793",
    "password": "test"
}


### login student
POST http://localhost:5000/api/student/login
Content-Type: application/json

{
    "studentID": "01620106003",
    "password": "test"
}


### my profile
GET http://localhost:5000/api/student/profile
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzMyMmI1Mjg1MmM2OTNhZjIwYzE0OSIsInN0dWRlbnRJRCI6IjAxNjIwMTA2MDAzIiwibmFtZSI6IlN0dWRlbnQgMyIsImlhdCI6MTY2NDI5NjgzMCwiZXhwIjoxNjY0MzAwNDMwfQ.fkhRPMFDQ-D9D6QOm7EopKaE-S6Yg5bKebjGKK3NbHc


### payment
PUT http://localhost:5000/api/student/payment
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzMyMmI1Mjg1MmM2OTNhZjIwYzE0OSIsInN0dWRlbnRJRCI6IjAxNjIwMTA2MDAzIiwibmFtZSI6IlN0dWRlbnQgMyIsImlhdCI6MTY2NDI5NjE2NCwiZXhwIjoxNjY0Mjk5NzY0fQ.ROzq3sRPtj1AwaWOdDulTxZV0QRmipB0VWOVRhbjX-M

{
    "transactionID": "TEST_TEST_2"
}


### tShirtSize
PUT http://localhost:5000/api/student/tShirt
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzMyMmI1Mjg1MmM2OTNhZjIwYzE0OSIsInN0dWRlbnRJRCI6IjAxNjIwMTA2MDAzIiwibmFtZSI6IlN0dWRlbnQgMyIsImlhdCI6MTY2NDI5NjgzMCwiZXhwIjoxNjY0MzAwNDMwfQ.fkhRPMFDQ-D9D6QOm7EopKaE-S6Yg5bKebjGKK3NbHc

{
    "tShirtSize": "XXL"
}


### participation
PUT http://localhost:5000/api/student/participation
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzMyMmI1Mjg1MmM2OTNhZjIwYzE0OSIsInN0dWRlbnRJRCI6IjAxNjIwMTA2MDAzIiwibmFtZSI6IlN0dWRlbnQgMyIsImlhdCI6MTY2NDI5NjgzMCwiZXhwIjoxNjY0MzAwNDMwfQ.fkhRPMFDQ-D9D6QOm7EopKaE-S6Yg5bKebjGKK3NbHc

{
    "culturalProgram": true,
    "treasureHunt": false
}


### update profile
PUT http://localhost:5000/api/student/profile
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMzMyMmI1Mjg1MmM2OTNhZjIwYzE0OSIsInN0dWRlbnRJRCI6IjAxNjIwMTA2MDAzIiwibmFtZSI6IlN0dWRlbnQgMyIsImlhdCI6MTY2NDI5NjgzMCwiZXhwIjoxNjY0MzAwNDMwfQ.fkhRPMFDQ-D9D6QOm7EopKaE-S6Yg5bKebjGKK3NbHc

{
    "name": "",
    "phone": "01309897793"
}