### register student
POST http://localhost:5000/api/student/register
Content-Type: application/json

{
    "name": "Hello Nigga",
    "studentID": "01620106009",
    "batch": "16th",
    "password": "test"
}


### login student
POST http://localhost:5000/api/student/login
Content-Type: application/json

{
    "studentID": "01620106009",
    "password": "test"
}


### get student details
GET http://localhost:5000/api/student/details
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzMjVkMjRmNzdhYjY2NGIzOWI4ZTEzZCIsInN0dWRlbnRJRCI6IjAxNjIwMTA2MDA5IiwibmFtZSI6IkhlbGxvIE5pZ2dhIiwiYmF0Y2giOiIxNnRoIiwiaXNQYWlkIjpmYWxzZSwiaWF0IjoxNjYzNDIzMzMwLCJleHAiOjE2NjM0MjY5MzB9.abjKarmU9STegOsscURmcEQ8tLONkRFIpvOZRVbVtIo
